-   id: tmt-test-lint
    name: tmt tests lint
    entry: bash -c "git ls-files --error-unmatch .fmf/version && tmt tests lint"
    files: '.*\.fmf'
    verbose: true
    pass_filenames: false
    language: python
    language_version: python3
