name: build_image
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ls
      - name: Buildah Build - tmt
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: tmt-all
          tags: latest
          containerfiles: ./containers/Containerfile.mini
