name: build_image
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Buildah Build - tmt
        uses: redhat-actions/buildah-build@v2.13
        id: build-image-tmt
        with:
          image: tmt
          tags: latest
          containerfiles: ./containers/Dockerfile.mini
      - name: Push To quay.io - tmt
      id: push-to-quay-tmt
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image-tmt.outputs.image }}
        tags: ${{ steps.build-image-tmt.outputs.tags }}
        registry: quay.io/lzachar/
        username: lzachar+github
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
