name: sleeper
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  sleeper:
    runs-on: ubuntu-latest
    steps:
      - id: sleeper
        name: sleeper
        run: sleep 60
